# -*- coding: utf-8 -*-
"""Ensemble_CNN_FashionMNIST.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O7u4Hyu5zolcybeDoMtXb5xEB8puq3wo
"""

import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

print("TensorFlow version:", tf.__version__)

(x_train, y_train), (x_test, y_test) = keras.datasets.fashion_mnist.load_data()

print("Original training data:", x_train.shape)
print("Original test data:", x_test.shape)

x_train = x_train[:50]
y_train = y_train[:50]

x_test = x_test[:50]
y_test = y_test[:50]

print("Training data:", x_train.shape)
print("Test data:", x_test.shape)

x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

x_train = x_train.reshape(-1, 28, 28, 1)
x_test = x_test.reshape(-1, 28, 28, 1)

print("Training shape:", x_train.shape)
print("Test shape:", x_test.shape)

X_train, X_val, y_train_split, y_val = train_test_split(
    x_train,
    y_train,
    test_size=0.2,
    random_state=42,
    stratify=y_train
)

print("Training samples:", len(X_train))
print("Validation samples:", len(X_val))

def create_cnn_model():

    model = keras.Sequential([
        layers.Conv2D(
            32,
            (3, 3),
            activation="relu",
            input_shape=(28, 28, 1)
        ),

        layers.MaxPooling2D((2, 2)),

        layers.Flatten(),

        layers.Dense(10, activation="softmax")
    ])

    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model

num_models = 5
ensemble_models = []

for i in range(num_models):

    print(f"\nTraining Model {i + 1}/5")

    # Bootstrap sampling
    indices = np.random.choice(
        len(X_train),
        size=len(X_train),
        replace=True
    )

    X_bootstrap = X_train[indices]
    y_bootstrap = y_train_split[indices]

    # Create CNN
    model = create_cnn_model()

    # Train
    model.fit(
        X_bootstrap,
        y_bootstrap,
        epochs=3,
        batch_size=8,
        verbose=1
    )

    ensemble_models.append(model)

val_predictions = []
test_predictions = []

for model in ensemble_models:

    val_pred = model.predict(X_val, verbose=0)
    test_pred = model.predict(x_test, verbose=0)

    val_predictions.append(val_pred)
    test_predictions.append(test_pred)

val_predictions = np.array(val_predictions)
test_predictions = np.array(test_predictions)

# Average predictions
ensemble_val_prob = np.mean(val_predictions, axis=0)
ensemble_test_prob = np.mean(test_predictions, axis=0)

# Final class
ensemble_val_pred = np.argmax(ensemble_val_prob, axis=1)
ensemble_test_pred = np.argmax(ensemble_test_prob, axis=1)

# Accuracy
ensemble_val_accuracy = accuracy_score(
    y_val,
    ensemble_val_pred
)

ensemble_test_accuracy = accuracy_score(
    y_test,
    ensemble_test_pred
)

print("Ensemble Validation Accuracy:", ensemble_val_accuracy)
print("Ensemble Test Accuracy:", ensemble_test_accuracy)

single_model = create_cnn_model()

single_model.fit(
    X_train,
    y_train_split,
    epochs=3,
    batch_size=8,
    verbose=1
)

single_val_prob = single_model.predict(X_val, verbose=0)
single_test_prob = single_model.predict(x_test, verbose=0)

single_val_pred = np.argmax(single_val_prob, axis=1)
single_test_pred = np.argmax(single_test_prob, axis=1)

single_val_accuracy = accuracy_score(
    y_val,
    single_val_pred
)

single_test_accuracy = accuracy_score(
    y_test,
    single_test_pred
)

print("Single Model Validation Accuracy:", single_val_accuracy)
print("Single Model Test Accuracy:", single_test_accuracy)

print("=" * 50)
print("FINAL RESULTS")
print("=" * 50)

print(f"Ensemble Validation Accuracy : {ensemble_val_accuracy:.4f}")
print(f"Ensemble Test Accuracy       : {ensemble_test_accuracy:.4f}")

print(f"Single Model Validation Accuracy : {single_val_accuracy:.4f}")
print(f"Single Model Test Accuracy       : {single_test_accuracy:.4f}")